# Generated by Django 5.1.3 on 2024-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_auth_status_followingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
