# Generated by Django 5.1.3 on 2024-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
